### ISSUE TITLE
xr_reproject is broken when warping across projected/geographic CRSs

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#109]
reprojecting from geographic to projected or other way fails due to mismatch in dimension names used by datacube for these two projections (xy vs lonlat).

Problematic code is here:
https://github.com/opendatacube/odc-tools/blob/f313310f1ab4711f09efffe5ef6bbddca9f4b88a/libs/algo/odc/algo/_warp.py#L180-L183

Code above assumes that "xy" coordinate names do not change between source and destination, but they do.

**Comment by robbibt** [comment]
There is an example of this issue in the "Reproject datacube data" section of this notebook here:

https://github.com/GeoscienceAustralia/dea-notebooks/blob/733cd13c8ebc98ee961d7b984bc4db01f450e3e6/Testing/Reprojecting_data.ipynb

In that example, we need to rename the dims on `ds` in order to use `xr_reproject` (even though this dataset does not have latitude/longitude dimensions until _after_ we apply `xr_reproject`):

```
# This works
if raster.geobox.crs.geographic:
    ds = ds.rename({'x': 'longitude', 'y': 'latitude'})
    ds_reprojected = xr_reproject(src=ds, geobox=raster.geobox)
```

**Comment by robbibt** [comment]
Note that the reverse example ("Reprojecting a raster to match datacube data" at the bottom of the notebook) works correctly without needing to rename dimension names on either `ds` or `raster`, e.g.: 

```
# Load data from datacube
ds = dc.load(
    product="ga_ls8c_ard_3",
    measurements=["nbart_red", "nbart_green", "nbart_blue"],
    time=("2019-01-10", "2019-01-15"),
    x=(149.10, 149.18),
    y=(-35.22, -35.35),
    resolution=(-30, 30),
    output_crs="EPSG:3577",
    group_by="solar_day",
)

# Load raster, and remove redundant "band" dimension
raster = xr.open_rasterio("../Supplementary_data/Reprojecting_data/canberra_dem_250m.tif").squeeze("band", drop=True)

# Reproject raster to match satellite datacube data
raster_reprojected = xr_reproject(src=raster, geobox=ds.geobox, resampling='average')
```
