### ISSUE TITLE
odc-geo repo?

### ISSUE THREAD

**Issue by snowman2** [opendatacube/odc-tools#58]
Thoughts on moving geospatial tools to a separate package/repository (maybe odc-geo)?

Maybe combine:
1. `opendatacube-core` geobox functionality
2. reprojection utilities here: https://github.com/opendatacube/odc-tools/blob/develop/libs/algo/odc/algo/_warp.py
3. Other?

This would be useful for the geospatial xarray community. For example, the geobox stuff is used in [geocube](https://github.com/corteva/geocube) and the dask supported reprojection stuff would be a nice engine to use in [rioxarray](https://github.com/corteva/rioxarray).

**Comment by Kirill888** [comment]
In general I agree Alan. I think moving some of the lower level functionality into a separate library will benefit `datacube` users as well as allowing easier re-use by other projects in geospatial space. We might even get larger contributor base for "simpler library" without all the database hurdle that new users of `datacube` need to deal with.

It will be a significant refactor and will take quite a bit of developer time, so this is not something I can commit to on my own. I will raise this proposal with members of ODC Steering Council. And while I do not expect resistance to this proposal, I do expect that it won't happen quickly, as there are currently some high-priority tasks that won't be finished soon. We can probably justify including this in ODC 2.0 work.

On a technical level this will involve moving geometry and xarray related utilities out of `datacube-core` into a stand-alone library, then moving some of the `odc-tools` libraries there as well. Tests will need to move as well, new tests might need to be written as I won't be surprised if some of the coverage comes from integration tests rather than unit-tests. Various utilities used by those tests will need to be moved too. Ideally I would like to keep commit history as well. So it's a sizeable amount of work to undertake, and probably best done by folks already familiar with the current codebase.

pinging some ODC people for visibility:

@alexgleith @woodcockr @gamedaygeorge @GypsyBojangles

**Comment by snowman2** [comment]
- https://github.com/opendatacube/datacube-core/issues/1084
- https://github.com/opendatacube/datacube-core/issues/519

In case you are interested, `rioxarray` might be a helpful tool for managing CRS/nodata/transform geospatial information:
- https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html
- https://corteva.github.io/rioxarray/stable/getting_started/nodata_management.html

**Comment by Kirill888** [comment]
FYI: @snowman2 
https://github.com/opendatacube/datacube-core/wiki/ODC-EP-06---Extract-Geometry-Utilities-into-a-Separate-Package

**Comment by RichardScottOZ** [comment]
Thanks Kirill.

**Comment by Kirill888** [comment]
Work starting here: https://github.com/opendatacube/odc-geo

**Comment by snowman2** [comment]
Thanks @Kirill888 :+1:
