### ISSUE TITLE
Compatibility issue - python version and aiohttp

### ISSUE THREAD

**Issue by GeoFelpave** [opendatacube/odc-tools#589]
### Expected behaviour

When adding odc-apps-dc-tools-0.2.14 there is an issue with aiohttp if the version of python is greater than 3.10. The main reason for this is that aiohttp for python >3.10 is currently in beta as per info here: https://github.com/aio-libs/aiohttp/issues/7675 which means that odc-apps-dc-tools-0.2.14 does not install as expected

### Actual behaviour

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

### Steps to reproduce the behaviour

mamba env create -f conda-environment.yml
pip install odc-apps-dc-tools

### Environment information

As per the .yml file here: https://github.com/opendatacube/datacube-core/blob/develop/conda-environment.yml

**Comment by SpacemanPaul** [comment]
We would be very reluctant to pin a maximum Python version because of an upstream library issue (especially if a fix to said issue is expected imminently).

Suggested workarounds:

1. The `conda-environment.yml` file  in core is intended as an example, to be edited according to your needs.  You could make a copy of this environment file and edit to read e.g. `- python ==3.10`

2. OR as @omad pointed out in your core issue, the following runs without error and results a Python3.11 environment with the latest releases of datacube, odc-apps-dc-tools and aiohttp:

```
mamba create -n newenv python=3.11 odc-apps-dc-tools 
mamba activate newenv
pip install --upgrade odc-apps-dc-tools
```
